name: linux
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage
    - name: Install dependencies2
      run: |
        pip install natsort numpy matplotlib
        pip install qtpy qtawesome
        pip install scikit-image
        pip install pylustrator --no-deps
    - name: Test
      env:
        QT_DEBUG_PLUGINS: 1
      run: |
        ulimit -c unlimited
        pytest
